### PR TITLE
Don't panic for unknown events in xproto

### LINKED ISSUE #141: Crash on unresolved xproto event
This occurred when running using the program as a window manager. It seems to have received the `x::StoreColors` request as an event which it then attempted and failed to parse. I'm not sure whether receiving requests as events is expected when running as a window manager or whether this is a bug earlier in the parsing and the response_type is nonsensical.

The issue is reproducible for me when in version <https://github.com/pr2502/mwm/tree/9498d9640f199ea6080aa11542973bfbca93763f> running `./run.sh` to run a debug build in Xephyr and then opening rofi with `DISPLAY=:3 rofi -show window`.

### Backtrace
<details><pre>
thread 'main' panicked at 'internal error: entered unreachable code: Could not resolve xproto Event with response_type 89 and first_event 0', ./target/debug/build/xcb-f88379ca782dda16/out/xproto.rs:5074:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8f3238f898163f09726c3d2b2cc9bafb09da26f3/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/8f3238f898163f09726c3d2b2cc9bafb09da26f3/library/core/src/panicking.rs:107:14
   2: <xcb::xproto::Event as xcb::base::ResolveWireEvent>::resolve_wire_event
             at ./target/debug/build/xcb-f88379ca782dda16/out/xproto.rs:5074:18
   3: xcb::event::resolve_event
             at home/.cargo/git/checkouts/rust-xcb-35c0c23e290e4816/afeaee7/src/event.rs:233:14
   4: xcb::base::Connection::handle_wait_for_event
             at home/.cargo/git/checkouts/rust-xcb-35c0c23e290e4816/afeaee7/src/base.rs:1134:16
   5: xcb::base::Connection::wait_for_event
             at home/.cargo/git/checkouts/rust-xcb-35c0c23e290e4816/afeaee7/src/base.rs:1186:13
   6: mwm_xcb::xcb_event_systems::wait_for_xcb_events
             at ./mwm_xcb/src/xcb_event_systems.rs:26:14
   7: core::ops::function::Fn::call
             at /rustc/8f3238f898163f09726c3d2b2cc9bafb09da26f3/library/core/src/ops/function.rs:70:5
   8: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /rustc/8f3238f898163f09726c3d2b2cc9bafb09da26f3/library/core/src/ops/function.rs:247:13
   9: <Func as bevy_ecs::system::into_system::SystemParamFunction<(),Out,(F0,),()>>::run
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/system/into_system.rs:207:21
  10: <bevy_ecs::system::into_system::FunctionSystem<In,Out,Param,Marker,F> as bevy_ecs::system::system::System>::run_unsafe
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/system/into_system.rs:147:19
  11: <bevy_ecs::system::system_chaining::ChainSystem<SystemA,SystemB> as bevy_ecs::system::system::System>::run_unsafe
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/system/system_chaining.rs:54:19
  12: bevy_ecs::schedule::executor_parallel::ParallelExecutor::prepare_systems::{{closure}}
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/schedule/executor_parallel.rs:200:30
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8f3238f898163f09726c3d2b2cc9bafb09da26f3/library/core/src/future/mod.rs:84:19
  14: async_executor::Executor::spawn::{{closure}}
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:144:19
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8f3238f898163f09726c3d2b2cc9bafb09da26f3/library/core/src/future/mod.rs:84:19
  16: async_task::raw::RawTask<F,T,S>::run
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/raw.rs:489:20
  17: async_task::runnable::Runnable::run
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/runnable.rs:309:18
  18: async_executor::Executor::try_tick
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:181:17
  19: bevy_tasks::task_pool::TaskPool::scope::{{closure}}
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.5.0/src/task_pool.rs:222:21
  20: std::thread::local::LocalKey<T>::try_with
             at /rustc/8f3238f898163f09726c3d2b2cc9bafb09da26f3/library/std/src/thread/local.rs:412:16
  21: std::thread::local::LocalKey<T>::with
             at /rustc/8f3238f898163f09726c3d2b2cc9bafb09da26f3/library/std/src/thread/local.rs:388:9
  22: bevy_tasks::task_pool::TaskPool::scope
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.5.0/src/task_pool.rs:169:9
  23: <bevy_ecs::schedule::executor_parallel::ParallelExecutor as bevy_ecs::schedule::executor::ParallelSystemExecutor>::run_systems
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/schedule/executor_parallel.rs:121:9
  24: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/schedule/stage.rs:822:17
  25: bevy_ecs::schedule::Schedule::run_once
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/schedule/mod.rs:201:13
  26: <bevy_ecs::schedule::Schedule as bevy_ecs::schedule::stage::Stage>::run
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/schedule/mod.rs:219:21
  27: bevy_app::app::App::update
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.5.0/src/app.rs:58:9
  28: mwm::main::{{closure}}
             at ./mwm/src/main.rs:14:13
  29: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/8f3238f898163f09726c3d2b2cc9bafb09da26f3/library/alloc/src/boxed.rs:1825:9
  30: bevy_app::app::App::run
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.5.0/src/app.rs:68:9
  31: bevy_app::app_builder::AppBuilder::run
             at home/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.5.0/src/app_builder.rs:49:9
  32: mwm::main
             at ./mwm/src/main.rs:10:5
  33: core::ops::function::FnOnce::call_once
             at /rustc/8f3238f898163f09726c3d2b2cc9bafb09da26f3/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</pre></details>

### PR DESCRIPTION
**Pull request by pr2502**
This changes the `ResolveWireEvent::resolve_wire_event` to return an Option. If we assume the X server is not misbihaving it's only possible for the base xproto to get an unparseable event (if the extension the event is from is not currently enabled) so I left the unreachable! in the other ones (and used unwrap on the options in `src/event.rs:resolve_event`).

Closes #141

### CODE REVIEW

**Comment by rtbo** [comment]
Thank for the PR.
Everything looks good to me except that `Event::Unknown` should carry the mut pointer to `xcb_generic_event` for letting the possibility to treat the event in a custom way. 
`Event` should also have a custom `Drop` implementation to free this unresolved event and avoid memory leak. `Event::Unresolved` would also work BTW.

**Comment by pr2502** [comment]
Embedding the pointer directly into the enum had the undesired side-effect that the `Drop` impl prevented users moving out (this was even triggered within the `xcb` codebase) of the whole enum which I think would make the API less ergonomic to use.

Instead I've added a wrapper type which implements `BaseEvent` and `Drop`.

File: src/event.rs [hunk 1]
```diff
@@ -106,6 +106,49 @@ pub enum Event {
...
+}
+
+/// an event was not recognized as part of the core protocol or any enabled extension
+pub struct UnresolvedEvent {
+    raw: *mut xcb_generic_event_t,
+}
+
+impl BaseEvent for UnresolvedEvent {
+    const EXTENSION: Option<Extension> = None;
+    const NUMBER: u32 = u32::MAX;
```
Comment (pr2502) [inline src/event.rs:121]: This is the one thing I'm not sure about, I couldn't find any usages of the constant on `BaseEvent` within `xcb`, I hope a dummy value is acceptable here.

**Comment by pr2502** [comment]
Alternative would be to not implement the `BaseEvent` trait for `UnresolvedEvent` and only provide an `as_raw` and `into_raw` methods on the type itself.

File: src/event.rs (hunk 1 above)
Comment (rtbo) [reply src/event.rs:121]: `BaseEvent::NUMBER` is in fact not used. For the time being, I don't see anything better than this.

**Comment by rtbo** [comment]
> Alternative would be to not implement the `BaseEvent` trait for `UnresolvedEvent` and only provide an `as_raw` and `into_raw` methods on the type itself.

This would work too, but the [`x::SendEvent`](https://rust-x-bindings.github.io/rust-xcb/branches/v1.0-dev/xcb/x/struct.SendEvent.html) request expects an event implementing `BaseEvent`, so it would disable the possibility for someone to craft an event from scratch and send it to the server.

In this regards, `Unknown` is better than `Unresolved`. (the user crafts a C event, cast it to `*mut xcb_generic_event_t` and wraps it into a `UnknownEvent` to send to `x::SendEvent`)
Sorry for going back and forth. Naming things is hard and I'm targetting v1.0 very soon, so I can't go back after.

**Comment by pr2502** [comment]
Ok, that's no problem.

File: src/event.rs [hunk 2]
```diff
@@ -106,6 +106,49 @@ pub enum Event {
...
+        std::mem::forget(self);
+        raw
+    }
+
+    fn as_raw(&self) -> *mut xcb_generic_event_t {
+        self.raw
+    }
+
+    fn as_slice(&self) -> &[u8] {
+        &[]
```
Comment (rtbo) [inline src/event.rs:138]: This is incorrect.
The purpose of `as_slice` is to provide the raw event data in the form of `[u8]`.
I would agree that the name could be better chosen (I will probably change this before the final release)

Comment (pr2502) [reply src/event.rs:138]: I understood the purpose of the method but i thought that since we don't know what the concrete type is we can't know how much we can safely read from the pointer so opted for the safest variant. Is there a way to know without resolving the concrete event type?

Comment (rtbo) [reply src/event.rs:138]: You can see [here](https://rust-x-bindings.github.io/rust-xcb/branches/v1.0-dev/src/xcb/home/runner/work/rust-xcb/rust-xcb/target/debug/build/xcb-8df0b2892b11bc21/out/xproto.rs.html#602) for an example. (for the length, `BaseEvent` by definition are 32 bytes long)

Comment (pr2502) [reply src/event.rs:138]: Ah ok, should I implement the Wired trait for it then as well? Also now I'm thinking, is there a posibility that the unresolved event was not a base event but a ge event, if it likely belonged to a disabled extension where ge events are used?

Comment (rtbo) [reply src/event.rs:138]: `Wired` is not strictly necessary. It is used to serialize/deserialize structs and values. In the case of `x::SendEvent`, the event is serialized using `as_slice` (see [here](https://rust-x-bindings.github.io/rust-xcb/branches/v1.0-dev/src/xcb/home/runner/work/rust-xcb/rust-xcb/target/debug/build/xcb-8df0b2892b11bc21/out/xproto.rs.html#14194))

Regarding GE events, they all have `response_type == XCB_GE_GENERIC`. In your current code, unresolved GE events would panic. (see [here](https://github.com/pr2502/rust-xcb/blob/ae0f2ed385fbd0b9908ac241c20fc5286f1ed934/src/event.rs#L174))

Comment (rtbo) [reply src/event.rs:138]: > we can't know how much we can safely read from the pointer so opted for the safest variant

This is a good remark. The only way for the user to construct `UnknownEvent` is `BaseEvent::from_raw`, which is unsafe.
I will add in the safety doc section that the data must be 32 bytes long. This is implied by being a valid event though.

Comment (pr2502) [reply src/event.rs]: thank you a lot for the explanation and links! i've implemented it now and included comments to hopefully make it clear why is it ok to read 32 bytes there

**Comment by rtbo** [comment]
All good thanks
